###
### Enable sudo (required for docker service)
###
sudo: required


###
### Attach services
###
services:
  - docker


###
### Global variables
###
env:
  matrix:
    - DEBUG=0
    - DEBUG=1
    - DEBUG=2


###
### Show information
###
before_install:
  # List versions
  - docker version
  - docker-compose version
  - whoami
  - groups
  - uname -a


###
### Disable any provided services
###
before_script:

  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop || true
  - sudo /etc/init.d/postgresql stopA || true
  - sudo service mysql stop || true
  - sudo service postgresql stop || true


###
### Test
###
script:
  - build/docker-validate.sh "${DEBUG}"
