###
### Enable sudo (required for docker service)
###
sudo: required


###
### Attach services
###
services:
  - docker


###
### Global variables
###
env:
  matrix:
    - DEBUG=0
    - DEBUG=1
    - DEBUG=2


###
### Show information
###
before_install:
  # Get newer docker version
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; then break; else i=$((i+1)); fi done
  # Get newer docker-compose version
  - curl -L --retry 100 --retry-max-time 0 https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv -f docker-compose /usr/local/bin
  # List versions
  - docker version
  - docker-compose version


###
### Disable any provided services
###
before_script:

  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop || true
  - sudo /etc/init.d/postgresql stop || true
  - sudo service mysql stop || true
  - sudo service postgresql stop || true


###
### Test
###
script:
  - build/docker-validate.sh "${DEBUG}"
